version: '3'

services:
  app:
    build: ./App
    ports:
      - 8080:8080
    volumes:
      - ./App/src:/usr/app/src
      - ./App/public:/usr/app/public
    depends_on:
      - vueapp
    stdin_open: true
    tty: true
  vueapp:
    build: ./VueApp/server
    ports:
      - 3080:3080
    volumes:
      - ./VueApp/server:/usr/app/src
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: {}
